### ISSUE TITLE
[버그, 개선사항] 전투 시 발생되는 버그 및 개선사항 요청

### ISSUE THREAD

**Issue by lee1030cjs** [lee1030cjs/SemiProject_ActionRPG#18]
버그!

1. 공격이 안됩니다.

캐릭터 피격 후 공격이 안되다가 다시 피격당하면 일정 순간부터 공격이 가능합니다.

![공격안됨](https://user-images.githubusercontent.com/58832533/79061551-47eb5880-7ccc-11ea-9d1b-0de6f92517c7.png)

2. HP바가 줄지 않습니다.

AI가 인식하지 못한 상태에서 공격을 받아 죽으면 HP바가 줄어들지 않습니다.
이 문제는 한방에 죽어서 그런 것일 수도..

![AI가 인식 못 했을 때 뒤에서 죽이면 HP바가 안줄어듬](https://user-images.githubusercontent.com/58832533/79061562-63566380-7ccc-11ea-9c57-a16ba7b536f4.png)

3. 회피시 점프가 가능합니다.
 

![구르다 점프가능](https://user-images.githubusercontent.com/58832533/79061578-94cf2f00-7ccc-11ea-9ec4-ff2be9785fe0.png)

개선사항 요청!

1. 몬스터 비헤비어트리 개선이 필요합니다.
상황에 따른 동작과 랜덤동작이 적절하게 필요하겠네요 그리고 랜덤으로 딜레이시간만 줘도 괜찮겠습니다.

![애들이 다 똑같이 따라다니면서 움직임](https://user-images.githubusercontent.com/58832533/79061585-a0baf100-7ccc-11ea-8c50-d2fa3a26b9c3.png)

2. 시야에서 벗어날 시

시야에서 벗어나면 몬스터들이 동시에 멈춥니다. 단체로 동시에 멈추니 부자연스럽네요 ㅠ

![잘 따라오다가 시야 옆으로 가니까 바로 멈춤](https://user-images.githubusercontent.com/58832533/79061610-ec6d9a80-7ccc-11ea-80ac-694200ddc1e9.png)

**Comment by ajantang** [comment]
버그 - 1. 수정 완료

개선 사항 - 2. 잘 보시면 몬스터가 nav mesh 밖으로 이동한 플레이어를 못 따라가서 서 있는겁니다. 개선 방향은 두 가지 중 하나 인데, 첫 째는 일정 시간 기다리다가 원 위치로 돌아가는것. 두 번째는 nav mesh를 늘려주는 것 입니다. 일단 첫 번째 안으로 수정 작업 하겠습니다.

**Comment by lee1030cjs** [comment]
수정사항 모두 확인했습니다. 고생하셨습니다!
