### ISSUE TITLE
hp/satamina 임시 ui 요청

### ISSUE THREAD

**Issue by ajantang** [lee1030cjs/SemiProject_ActionRPG#2]
높이 180
너비 10~15

가로로 누운 직사각형 기반의 ui 프레임 요청

요구사항 1. hp/stamina에 따라 변경될 가운데 부분은 투명하게 설정

**Comment by ajantang** [comment]
https://www.youtube.com/watch?v=7e2LIOdG9NU - 젤다의 전설 스태미너 ui 제작 참고

**Comment by ajantang** [comment]
https://www.youtube.com/watch?v=HNgKcJmiIss - HP 바 UI 제작 참고

**Comment by lee1030cjs** [comment]
확인했습니다.
