### ISSUE TITLE
[리소스 요청] 퍼즐 리소스 요청

### ISSUE THREAD

**Issue by uknim2000** [lee1030cjs/SemiProject_ActionRPG#4]
1.텔레포트 포인트 애셋 
2.빛, 기둥 애셋
없으면 그려서라도

**Comment by lee1030cjs** [comment]
퍼즐에 관련된 이펙트 리소스 확보했습니다.

레벨에서는 선 작업으로 더미만 완료해주시고

이를 바탕으로 퍼즐 기획자가 보유한 리소스를 가지고 퍼즐맵을 완성시키겠습니다.
