### ISSUE TITLE
이펙트 관련 리소스 요청

### ISSUE THREAD

**Issue by ajantang** [lee1030cjs/SemiProject_ActionRPG#5]
기믹에 사용할 오브젝트/이펙트 용 리소스 요청
 - mesh
 - effect
 - material
 - texture
 - blueprint

**Comment by lee1030cjs** [comment]
리소스확보 완료했습니다.
해당 리소스는 깃 프로젝트 폴더에 통으로 추가시킨 상태이며
필요한 이펙트를 선정 후 나머지는 삭제하는 것으로 하겠습니다.
